# Produces win32 executable.

CC=gccwin
CFLAGS=-O2
LD=ldwin
LDFLAGS=
AS=aswin
AR=arwin
COPTS=-S $(CFLAGS) -ansi -I. -I../bios -I../pdpclib -I../src -U__WIN32__ -D__PDOS386__ -DNOLIBALLOC -D__NOBIVA__

all: clean pdos.exe

pdos.exe: pdos.o ../bios/exeload.o genstart.o
    $(LD) $(LDFLAGS) -s -e ___crt0 -o pdos.exe genstart.o pdos.o ../bios/exeload.o ../pdpclib/pdosgeno.a

.c.o:
    $(CC) $(COPTS) -o $*.s $<
    $(AS) -o $@ $*.s
    rm -f $*.s

clean:
    rm -f *.o pdos.exe
