# This builds EFI executables for the 80386

CC=gccwin
AR=arwin
LD=ldwin
AS=pdas -O coff
COPTS=-S -O2 -D__WIN32__ -D__NOBIVA__ -I.

TARGET=bootia32.efi
OBJS=efistart.o

$(TARGET): clean $(OBJS)
  $(LD) -s -subsystem efi -e _efimain -nostdlib -o $(TARGET) $(OBJS)

.c.o:
  $(CC) $(COPTS) -o $*.s $<
  $(AS) -o $*.o $*.s
  rm -f $*.s

clean:
  rm -f *.o
  rm -f $(TARGET)
