# This builds EFI (PE) executables for the ARM

CC=gccprm
AR=arprm
LD=ldprm
AS=asprm
COPTS=-S -O0 -mapcs-32 -fno-common -D__ARM__ -D__NOBIVA__ -I. -DEFITEST

TARGET=pdptest.efi

$(TARGET): efistart.o
  $(LD) -s -subsystem efi -e _efimain -nostdlib -o $(TARGET) efistart.o

.c.o:
  $(CC) $(COPTS) -o $*.s $<
  $(AS) -o $*.o $*.s
  rm -f $*.s

.asm.o:
  $(AS) -o $@ $<
