# This builds a PDOS-generic executable for the mainframe

CC=gcc370
COPTS=-S -Os -fno-common -U__MVS__ -D__MF32__ -D__PDOSGEN__ -D__NOBIVA__ -I . -I../generic

all: clean pdptest.exe

pdptest.exe: pgastart.o pdptest.o
  rm -f pdptest.exe
  pdld --oformat mainframe -e __crt0 -o pdptest.exe pgastart.o pdptest.o

.c.o:
  $(CC) $(COPTS) -o $*.s $<
  as370 -o $@ $*.s
  rm -f $*.s

.asm.obj:
  as370 -o $@ $<

clean:
  rm -f pdptest.exe
