# This builds EFI (PE) executables for the ARM

CC=gccprm
AR=arprm
LD=ldprm
AS=asprm
COPTS=-S -O2 -mapcs-32 -D__ARM__ -D__NOBIVA__ -I.

pdptest.exe: efistart.o
  $(LD) -s -subsystem efi -e _efimain -nostdlib -o pdptest.exe efistart.o

.c.o:
  $(CC) $(COPTS) -o $*.s $<
  $(AS) -o $*.o $*.s
  rm -f $*.s

.asm.o:
  $(AS) -o $@ $<
