# This builds a PDOS-generic executable

CC=gccwin
COPTS=-S -O2 -U__WIN32__ -D__PDOS386__ -D__PDOSGEN__ \
    -D__NOBIVA__ -I . -I../generic -I../src

all: clean pdptest.exe

pdptest.exe: pgastart.o pdptest.o
  rm -f pdptest.exe
  ldwin -s -e ___crt0 -o pdptest.exe pgastart.o pdptest.o

.c.o:
  $(CC) $(COPTS) -o $*.s $<
  aswin -o $@ $*.s
  rm -f $*.s

.asm.obj:
  aswin -o $@ $<

clean:
  rm -f pdptest.exe
